apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: flui-control
  labels:
    app: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/managed-by: flui-cloud
    app.kubernetes.io/instance: grafana
    flui.cloud/managed: "true"
    flui.cloud/scope: "app"
    flui.cloud/app-kind: "SYSTEM"
    flui.cloud/owner-kind: "application"
    flui.cloud/owner-id: "grafana"
    flui.cloud/app-slug: "grafana"
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        type: prometheus
        access: proxy
        url: http://vmsingle:8428
        isDefault: true
        editable: true
        jsonData:
          timeInterval: "30s"

      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        editable: true
        jsonData:
          maxLines: 1000
