apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flui-api-ingress
  namespace: default
  labels:
    app: flui-api
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: api.flui.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flui-api
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flui-web-ingress
  namespace: default
  labels:
    app: flui-web
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: app.flui.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flui-web
                port:
                  number: 80
