apiVersion: v1
kind: ConfigMap
metadata:
  name: flui-web-config
  namespace: default
  labels:
    app: flui-web
    app.kubernetes.io/name: flui-web
    app.kubernetes.io/managed-by: flui-cloud
    app.kubernetes.io/instance: flui-web
data:
  config.json: |
    {
      "apiUrl": "http://${MASTER_IP}:30080"
    }
